---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orderer
  namespace: orgorderer1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:latest
          volumeMounts:
            - name: blockchain-pvc-nfs
              mountPath: "/mnt"
      tolerations:
        - key: Endorsing
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: Kafka
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: blockchain-pvc-nfs
          persistentVolumeClaim:
            claimName: nfsdisk-orgorderer1
---
apiVersion: v1
kind: Service
metadata:
  name: ordering
  namespace: orgorderer1
  labels:
    app: ordering
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: ordering
