---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-orgorderer1
  namespace: orgorderer1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
