---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsdisk-orgorderer1
  namespace: orgorderer1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
