apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ca
  namespace: org1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ca
    spec:
      containers:
        - name: ca
          image: hyperledger/fabric-ca:latest
          volumeMounts:
            - name: blockchain-pvc-nfs
              mountPath: "/mnt"
      tolerations:
        - key: Ordering
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: Kafka
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: blockchain-pvc-nfs
          persistentVolumeClaim:
            claimName: nfsdisk
---
apiVersion: v1
kind: Service
metadata:
  name: ca
  namespace: org1
  labels:
    app: endorsing
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: ca
