---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: endorser
  namespace: org1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: endorser
    spec:
      containers:
        - name: peer
          image: hyperledger/fabric-peer:latest
          volumeMounts:
            - name: blockchain-pvc-nfs
              mountPath: "/mnt"
        - name: couchdb
          image: hyperledger/fabric-couchdb:latest
          volumeMounts:
            - name: blockchain-pvc-nfs
              mountPath: "/mnt"
      tolerations:
        - key: Ordering
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: Kafka
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: blockchain-pvc-nfs
          persistentVolumeClaim:
            claimName: filestore-org1
---
apiVersion: v1
kind: Service
metadata:
  name: endorsing
  namespace: org1
  labels:
    app: endorsing
spec:
  type: ClusterIP
  ports:
    - name: port-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: port-30303
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: port-30304
      protocol: TCP
      port: 30304
      targetPort: 30304
  selector:
    app: endorsing
