---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orderer
  namespace: org1-orderer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:latest
      tolerations:
        - key: Endorsing
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: Kafka
          operator: Equal
          value: "true"
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: ordering
  namespace: org1-orderer
  labels:
    app: ordering
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: ordering
