---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-org1
  namespace: org1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
