---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsdisk
  namespace: org1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
