---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: peer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: peer
    spec:
      containers:
      - name: peer
        image: hyperledger/fabric-peer:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: peer
        image: hyperledger/fabric-couchdb:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: endorsing
  labels:
    app: endorsing
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: endorsing
