---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: hyperledger/fabric-kafka:latest
          ports:
            - containerPort: 9092
        - name: zookeeper
          image: hyperledger/fabric-zookeeper:latest
          ports:
            - containerPort: 2181
      tolerations:
        - key: Endorsing
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: Ordering
          operator: Equal
          value: "true"
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
